name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: write-all

jobs:
  speak:
    name: speak
    runs-on: ubuntu-latest

    steps:
    - name: Echo a message
      run: echo "Pytest and Pylint is running!"

  marking:
    name: pytest and pylint
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v4

    # Install Python
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    # Install required packages
    - name: Install packages
      run: |
        pip install -r ./collect_metadata/requirements.txt
        pip install -r ./short_term/requirements.txt
        pip install -r ./long_term/requirements.txt

    - name: Run pytest
      run: |
        pytest
      continue-on-error: false

    - name: Lint
      run: |
        find . -name "*.py" | xargs pylint --fail-under=8